#!/bin/bash



  
    # Объявляем переменную со значением 4
    choice=4
    # Выводим на экран
    echo "1. Создать"
    echo "2. Переместить"
    echo "3. Удалить"
    echo -n "Выберите операцию над файлом [1,2 or 3]? "
    # Выполняем, пока переменная равна четырем
    # Зацикливание
    while [ $choice -eq 4 ]; do

    # читаем пользовательский ввод
    read choice
    # вложенное "если-иначе" условие
    if [ $choice -eq 1 ] ; then

            echo "Вы собираетесь: Создать файл"
	    echo "Введите имя файла"
		read name1
	
		if [ -f $name1 ] ; then
    echo "Файл уже существует"
fi
		touch $name1

    else                   




            if [ $choice -eq 2 ] ; then
                     echo "Вы собираетесь: Переместить файл"
		     echo "Введите имя файла"
		read name2
		 per1=$(ls -l | grep "$name2")
                        if [ "$per1" = "" ]; then
                        echo "Ошибка: файл не найден. Попробуйте снова"

                        fi
		 echo "Введите имя каталога, в который будет перемещен файл"
		 read way
		per2=$(ls -l | grep "$way")

			if [ "$per2" = "" ]; then
			echo "Ошибка: каталог не найден. Попробуйте снова"

			fi
		 cp $name2 $way
		 rm -f $name2
            else
            



                    if [ $choice -eq 3 ] ; then
                            echo "Вы собираетесь: Удалить файл"
			 echo "Введите имя файла"
                read name3
                 per3=$(ls -l | grep "$name3")
                        if [ "$per3" = "" ]; then
                        echo "Ошибка: файл не найден. Попробуйте снова"

                        fi
		rm -f $name3




                    else
                            echo "Пожалуйста, выберите пункт 1-3 !"
                            echo "1. Создать"
                            echo "2. Переместить"
                            echo "3. Удалить"
                            echo -n "Выберите операцию над файлом  [1,2 or 3]? "
                            choice=4
                    fi   
            fi
    fi
    done
